import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        primary: '#003ec7',
        'primary-container': '#0052ff',
        'primary-fixed': '#dde1ff',
        'primary-fixed-dim': '#b7c4ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#dfe3ff',
        'on-primary-fixed': '#001452',
        'on-primary-fixed-variant': '#0038b6',
        secondary: '#994700',
        'secondary-container': '#fb7800',
        'secondary-fixed': '#ffdbc8',
        'secondary-fixed-dim': '#ffb68b',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#592600',
        'on-secondary-fixed': '#321200',
        'on-secondary-fixed-variant': '#753400',
        tertiary: '#952200',
        'tertiary-container': '#bf3003',
        'tertiary-fixed': '#ffdbd2',
        'tertiary-fixed-dim': '#ffb4a1',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffddd5',
        'on-tertiary-fixed': '#3c0800',
        'on-tertiary-fixed-variant': '#891e00',
        background: '#fbf8ff',
        surface: '#fbf8ff',
        'surface-dim': '#d9d9e7',
        'surface-bright': '#fbf8ff',
        'surface-tint': '#004ced',
        'surface-variant': '#e1e1ef',
        'surface-container': '#ededfb',
        'surface-container-low': '#f3f2ff',
        'surface-container-high': '#e7e7f5',
        'surface-container-highest': '#e1e1ef',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#191b25',
        'on-surface-variant': '#434656',
        'on-background': '#191b25',
        outline: '#737688',
        'outline-variant': '#c3c5d9',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-surface': '#2e303a',
        'inverse-on-surface': '#f0effe',
        'inverse-primary': '#b7c4ff',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        gutter: '16px',
        margin: '24px',
        unit: '4px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      boxShadow: {
        card: '0 4px 12px rgba(0,82,255,0.05)',
        'card-hover': '0 8px 24px rgba(0,82,255,0.1)',
        nav: '0 4px 12px rgba(0,82,255,0.05)',
        'nav-bottom': '0 -4px 16px rgba(0,0,0,0.08)',
      },
    },
  },
  plugins: [],
};

export default config;
